Algoritmo "Exercicio_10"
//Crie um programa que receba do usuário um
//número e apresente a Tabuada deste.
Var
     i:inteiro
     tabuada:inteiro


Inicio
             escreval ("Digite um numero para Tabuada: ")
                leia(tabuada)
                escreval("TABUADA DE " , tabuada)
             

             para i de 1 ate tabuada faca
             escreval( i, " X ", tabuada, " = " ,(tabuada * i))


                fimpara

Fimalgoritmo