Algoritmo "Exercicio_14"
//Crie um programa que, imprima a tabuada de um
//número digitado pelo usuário
Var
     i:inteiro
     tabuada:inteiro


Inicio
             escreval ("Digite um numero para Tabuada: ")
                leia(tabuada)
                escreval("TABUADA DE " , tabuada)

               enquanto i < tabuada faca
               escreval( i, " X ", tabuada, " = " ,(tabuada * i))
                   i <- i+1



                 fimenquanto


Fimalgoritmo