Algoritmo "Exercicio_3"
//Crie um programa que receba um valor de depósito
//do usuário e atualize o seu saldo. Ao final exiba o
//valor inicial o depósito e o saldo atual



Var
   saldoInicial:real
   saldoDeposito:real

   


Inicio

   saldoInicial<-50
        escreval("Saldo inicial R$ ", saldoInicial)

   escreva ("Valor do deposito: ")
        leia (saldoDeposito)
   

        escreva ("Saldo total disponível R$ ", saldoInicial+saldoDeposito)


Fimalgoritmo